[pytest]
addopts = --screenshot=on --video=retain-on-failure --alluredir=./reports/allure-results
testpaths = tests
markers =
    web: marks tests as web ui tests (deselect with '-m "not web"')
    api: marks tests as api tests
    smoke: marks tests as smoke tests
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_date_format = %Y-%m-%d %H:%M:%S
